-- DROP EXISTING TABLES

DROP TABLE IF EXISTS quiz_session_questions CASCADE;
DROP TABLE IF EXISTS quiz_sessions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS public_broadcast_state CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- CREATE TABLES

-- Create users table with UUID linked to auth.users
CREATE TABLE users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  discriminator TEXT NOT NULL DEFAULT LPAD((('x' || SUBSTRING(replace(id::text, '-', ''), GREATEST(LENGTH(replace(id::text, '-', '')) - 7, 1), 8))::bit(32)::bigint % 10000)::text, 4, '0'),
  role TEXT DEFAULT 'user' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create questions table with timestamp fields
CREATE TABLE questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_answer_index INTEGER NOT NULL,
  start_timestamp INTEGER NOT NULL,
  end_timestamp INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create answers table
CREATE TABLE answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  selected_option INTEGER NOT NULL,
  is_correct BOOLEAN NOT NULL,
  score INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create quiz_sessions table
CREATE TABLE quiz_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE,
  total_score INTEGER DEFAULT 0,
  questions_count INTEGER DEFAULT 0
);

-- Create quiz_session_questions table
CREATE TABLE quiz_session_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT REFERENCES quiz_sessions(id) ON DELETE CASCADE,
  question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
  UNIQUE(session_id, question_id)
);

-- Create broadcast state table
CREATE TABLE public_broadcast_state (
  id BIGINT PRIMARY KEY DEFAULT 1,
  current_position DECIMAL NOT NULL DEFAULT 0,
  is_playing BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by UUID REFERENCES users(id),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CREATE FUNCTIONS

CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM users 
    WHERE id = auth.uid() 
    AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ENABLE ROW LEVEL SECURITY

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_session_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_broadcast_state ENABLE ROW LEVEL SECURITY;

-- CREATE RLS POLICIES

-- RLS Policies for users table
CREATE POLICY "Users can view all users" 
  ON users FOR SELECT 
  USING (true);

CREATE POLICY "Users can insert their own profile" 
  ON users FOR INSERT 
  TO authenticated
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
  ON users FOR UPDATE 
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- RLS Policies for questions table
CREATE POLICY "Anyone can read questions" 
  ON questions FOR SELECT 
  USING (true);

CREATE POLICY "Only admins can modify questions" 
  ON questions FOR ALL 
  USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid() 
      AND role = 'admin'
    )
  );

-- RLS Policies for answers table
CREATE POLICY "Users can insert their own answers" 
  ON answers FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own answers" 
  ON answers FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all answers" 
  ON answers FOR SELECT 
  USING (is_admin());

-- RLS Policies for quiz_sessions table
CREATE POLICY "Users can view their own sessions" 
  ON quiz_sessions FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own sessions" 
  ON quiz_sessions FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own sessions" 
  ON quiz_sessions FOR UPDATE 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can view all sessions" 
  ON quiz_sessions FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid() 
      AND role = 'admin'
    )
  );

-- RLS Policies for quiz_session_questions table
CREATE POLICY "Users can view their session questions" 
  ON quiz_session_questions FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM quiz_sessions 
      WHERE quiz_sessions.id = session_id 
      AND quiz_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their session questions" 
  ON quiz_session_questions FOR INSERT 
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM quiz_sessions 
      WHERE quiz_sessions.id = session_id 
      AND quiz_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Admins can view all session questions" 
  ON quiz_session_questions FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid() 
      AND role = 'admin'
    )
  );

-- RLS Policies for broadcast state
CREATE POLICY "Anyone can read broadcast state" 
  ON public_broadcast_state FOR SELECT 
  TO anon, authenticated
  USING (true);

CREATE POLICY "Only admins can update broadcast state" 
  ON public_broadcast_state FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM users 
      WHERE id = auth.uid() 
      AND role = 'admin'
    )
  );

-- CREATE INDEXES

CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_discriminator ON users(discriminator);
CREATE INDEX idx_users_name_discriminator ON users(name, discriminator);
CREATE INDEX idx_answers_user_id ON answers(user_id);
CREATE INDEX idx_answers_question_id ON answers(question_id);
CREATE INDEX idx_answers_score ON answers(score DESC);
CREATE INDEX idx_answers_created_at ON answers(created_at);
CREATE INDEX idx_quiz_sessions_user_id ON quiz_sessions(user_id);
CREATE INDEX idx_quiz_sessions_started_at ON quiz_sessions(started_at);
CREATE INDEX idx_quiz_session_questions_session_id ON quiz_session_questions(session_id);
CREATE INDEX idx_quiz_session_questions_question_id ON quiz_session_questions(question_id);
CREATE INDEX idx_public_broadcast_state_updated_at ON public_broadcast_state(updated_at DESC);
CREATE INDEX idx_questions_timestamps ON questions(start_timestamp, end_timestamp);

-- CONFIGURE REALTIME & PERMISSIONS

-- Configure realtime for broadcast state table
ALTER TABLE public_broadcast_state REPLICA IDENTITY FULL;
GRANT SELECT ON public_broadcast_state TO anon, authenticated;

-- Enable Realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public_broadcast_state;

INSERT INTO public_broadcast_state (id, current_position, is_playing)
VALUES (1, 0, false)
ON CONFLICT (id) DO NOTHING;
